### ISSUE TITLE
Automatic compilation

### ISSUE THREAD

**Issue by funkotron** [weavejester/duct-figwheel-component#1]
Is there a way to get figwheel to auto-compile when a file in a watch directory changes? (The same behaviour as the lein plugin)

**Comment by weavejester** [comment]
Not as part of this library, because it's simpler to have that functionality in a separate component, or as something that operates over the whole system.

For example, you could use a file watcher like [Hawk](https://github.com/wkf/hawk) to call your system reset function whenever it notices a file change:

``` clojure
(hawk.core/watch!
 [{:paths   ["src" "test" "resources"]
   :handler (fn [_ _] (reloaded.repl/reset))}])
```

Or you could write a component to do something similar:

``` clojure
(defrecord FileWatcher [paths make-handler]
  component/Lifecycle
  (start [component]
    (if (:watcher component)
      component
      (let [handler (make-handler component)
            watcher (hawk/watch! [{:paths paths, :handler handler}])]
        (assoc component :watcher watcher))))
  (stop [component]
    (if-let [watcher (:watcher component)]
      (do (hawk/stop! watcher) (dissoc component :watcher))
      component)))
```

I've been considering writing a library around this, but I haven't gotten around to it. The broad concept though is that the act of watching for file changes and then doing something is a fairly generic use-case. Rather than writing a custom file watcher for every compiler, it makes more sense to write a generic watcher that takes an arbitrary handler function instead.

**Comment by funkotron** [comment]
Thanks, https://github.com/danielsz/system contains a `hara.io.watch` component with a file watcher so I'll use that for now.

**Comment by freckletonj** [comment]
On a similar note, can I get a simple `(reset)` while within a `(cljs-repl)`?

I like using the cljs-repl from within emacs, and needing to `:cljs/quit` out of it in order to `(reset)` and `build` my .js assets is a bit tedious.

**Comment by weavejester** [comment]
@freckletonj, CIDER already has a command `cider-jack-in-clojurescript` that opens two REPLs, one for Clojure and one for ClojureScript.

The advantage of having two REPLs open is that you get code completion and evaluation for both the Clojure and ClojureScript parts of your application, as well as having access to `(reset)`.
